### ISSUE TITLE
Any chance or have you tried this on a z230 Tower not just sff workstations?

### ISSUE THREAD

**Issue by h9j6k** [matDOTviguier/z230nvmebios#1]
Hi Mat,

Thanks for your work. I was wondering if the method given on the readme page also works on a z230 tower machine. 

Thanks.

**Comment by matDOTviguier** [comment]
@h9j6k Z230 TW and Z230 SFF share the same BIOS PACK.

- 01.63 Rev.A BIOS white space _is_ into the same chip, via **the same** file **_ROM_ L51 v01.63 04/22/2020**

While I have no Tower to test, this hack should work well on Tower too.
It only depends on the MB chip that olds the ROM.
